deps:
  run:
    - curl -fL https://install-cli.jfrog.io | sh /dev/stdin 2.82.0
run:
  binary:
    source: https://github.com/harness/drone-artifactory/releases/download/{{ release }}/plugin-{{ os }}-{{ arch }}.zst